FTP_Sever:
  host: '14.116.177.18'# 127.0.0.1   14.116.177.18
  username: 'username1'
  password: '1PASSWORD'
  buffer_size: 204800
  port: '21'
Log_Path:
  cron_log_path: "log/cron.log"
  sever_log_path: "log/sever.log"
Douyin_Updata:
  base_asr_path: 'result/asr_data'
  # 爬虫文本数据
  ftp_file_path: 'ZMY/douyin.json'
  local_ftpfile_path: 'result/douyin_update'
  # 爬虫音频数据
  severMP3file_path: 'ZMY/mp3_file'
  localMP3file_path: 'ZMY/audio'
  # 准换后ASR数据
  localASRfile_path: 'ZMY/asr'
HOT_Trends:
  base_path: 'result/hot_tracking/'
  # 本地热榜数据
  hottrends_local_path: 'douyin_hot_top_keytops.json'
  hottrends_sever_path: '/JMZ/deal_douyin_search.json'
  # 本地热词搜索视频
  searchitem_local_path: '/deal_douyin_search.json'
  searchitem_sever_path: '/JMZ/search_keywords.json'
  # 本地热榜搜索词数据
  crawler_local_path: 'douyin_hot_tag_keywords.xls'
  crawler_sever_path: '/JMZ/douyin_keyword_search.json'
  # 本地热搜词视频数据
  crawlervideo_list_local_path: 'result_hot_insurance_data.json'
  crawlervideo_list_sever_path: '/JMZ/video.json'
  # 本地视频数据
  crawler_video_local_path: 'JMZ/audio'
  crawler_video_sever_path: '/JMZ/mp3_file'
XunFei_ASR:
  Long_Form_ASR:
    appid: ""
    secret_key: ""
    # 上传数据接口
    upload:
      # 接口配置
      lfasr_host: 'https://raasr.xfyun.cn/v2/api'
      api_upload: '/upload'
      api_get_result: '/getResult'
      # upload参数配置
      sysDicts: "advertisement"
      duration: 200
    download:
      # 下载数据接口
