FTP_Sever:
  host: '14.116.177.18'# 127.0.0.1
  username: 'username1'
  password: '1PASSWORD'
  buffer_size: 204800
  port: '21'
Log_Path:
  cron_log_path: "log/cron.log"
  sever_log_path: "log/sever.log"
Douyin_Updata:
  # 存储ASR数据的路径
  base_asr_path: 'result/asr_data/'
  # 爬虫文本数据
  server_txt_path: 'ZMY/hudao_douyin.json'
  local_txt_path: '/ZMY/hudao_douyin.json'
  # 爬虫音频数据
  severMP3file_path: 'ZMY/mp3_file'
  localMP3file_path: '/ZMY/audio'
  # 准换后ASR数据
  localASRfile_path: '/ZMY/asr'
HOT_Trends:
  base_path: 'result/hot_tracking/'
  sever_base_path: '/'
  # 本地热榜数据
  hotvideo_local_path: '/JMZ/hot_tracking/douyin_hot_video/'
  hotvideo_sever_path: '/JMZ/hot_tracking/douyin_hot_video/'
  # 本地热榜搜索词数据
  hotkeywords_local_path: '/JMZ/hot_tracking/douyin_hot_keywords/'
  hotkeywords_sever_path: '/JMZ/hot_tracking/douyin_hot_keywords/'
  # 本地热词搜索视频
  searchvideo_local_path: '/JMZ/hot_tracking/douyin_search_video/'
  searchvideo_sever_path: '/JMZ/hot_tracking/douyin_search_video/'
  # 本地热搜词视频数据
  recallvideo_local_path: '/JMZ/hot_tracking/douyin_recall_video/'
  recallvideo_sever_path: '/JMZ/hot_tracking/douyin_recall_video/'
  # 本地视频数据
  crawler_video_local_path: '/JMZ/audio'
  crawler_video_sever_path: '/JMZ/mp4_file'

  localASRfile_path: '/JMZ/asr'
  base_asr_path: 'result/asr_data/'
  # 热门关键短语中间文件路径
  hotkeywords_tmp_local_path: '/JMZ/hot_tracking/douyin_hot_keywords_tmp/'
  # 最终输入结果文件路径
  hottracking_result_local_path: '/JMZ/hot_tracking/douyin_result_video/'
  # 需要改写的视频数据
  rewriter_local_path: '/JMZ/hot_tracking/douyin_rewriter_result/'
XunFei_ASR:
  Long_Form_ASR:
    appid: "f5293126"
    secret_key: "d8089745806779226c538608d8bec698"
#    appid: "664f62a1"
#    secret_key: "56471ae04b9a3abe23d54e4ee235f585"
    # 上传数据接口
    upload:
      # 接口配置
      lfasr_host: 'https://raasr.xfyun.cn/v2/api'
      api_upload: '/upload'
      api_get_result: '/getResult'
      # upload参数配置
      sysDicts: "advertisement"
      duration: 200
    # 回调数据接口
    callbackUrl: "http://192.168.97.192:8010"


