FTP_Sever:
  host: '0.0.0.0'
  username: 'username1'
  password: '1PASSWORD'
  buffer_size: 204800
  port: '21'
  ftp_file_path: 'ftp'
  dst_file_path: 'test/local/'
MEIZHI:
  jmz_hottrends_path: ''
  jmz_searchitem_path: ''