FTP_Sever:
  host: '0.0.0.0'
  username: 'username1'
  password: '1PASSWORD'
  buffer_size: 204800
  port: '21'
Douyin_Updata:
  ftp_file_path: 'ftp'
  dst_file_path: 'test/local/'
HOT_Trends:
  # 本地热榜数据
  hottrends_local_path: './data/hot_tracking/douyin_hot_top_1024.json'
  hottrends_sever_path: ''
  # 本地热词搜索视频
  searchitem_local_path: './data/hot_tracking/deal_douyin_search_1024.json'
  searchitem_sever_path: ''
  # 本地热榜搜索词数据
  crawler_local_path: './result/hot_tracking/douyin_hot_tag_keywords_1024.xls'
  crawler_sever_path: ''
  # 本地热搜词视频数据
  crawlervideo_list_local_path: './data/hot_tracking/result_hot_insurance_data_1024.json'
  crawlervideo_list_sever_path: ''
  # 本地视频文案数据
  crawler_video_local_path: './result/hot_tracking/video_content'
  crawler_video_sever_path: ''